export const CATEGORY_PRODUCT_CREATE_REQUEST = "CATEGORY_PRODUCT_CREATE_REQUEST";
export const CATEGORY_PRODUCT_CREATE_SUCCESS = "CATEGORY_PRODUCT_CREATE_SUCCESS";
export const CATEGORY_PRODUCT_CREATE_FAIL = "CATEGORY_PRODUCT_CREATE_FAIL";
export const CATEGORY_PRODUCT_CREATE_RESET = "CATEGORY_PRODUCT_CREATE_RESET";

export const CATEGORY_PRODUCT_LIST_REQUEST = "CATEGORY_PRODUCT_LIST_REQUEST";
export const CATEGORY_PRODUCT_LIST_SUCCESS = "CATEGORY_PRODUCT_LIST_SUCCESS";
export const CATEGORY_PRODUCT_LIST_FAIL = "CATEGORY_PRODUCT_LIST_FAIL";

export const CATEGORY_PRODUCT_EDIT_REQUEST = "CATEGORY_PRODUCT_EDIT_REQUEST";
export const CATEGORY_PRODUCT_EDIT_SUCCESS = "CATEGORY_PRODUCT_EDIT_SUCCESS";
export const CATEGORY_PRODUCT_EDIT_FAIL = "CATEGORY_PRODUCT_EDIT_FAIL";

export const CATEGORY_PRODUCT_DELETE_REQUEST = "CATEGORY_PRODUCT_DELETE_REQUEST";
export const CATEGORY_PRODUCT_DELETE_SUCCESS = "CATEGORY_PRODUCT_DELETE_SUCCESS";
export const CATEGORY_PRODUCT_DELETE_FAIL = "CATEGORY_PRODUCT_DELETE_FAIL";

export const CATEGORY_PRODUCT_UPDATE_REQUEST = "CATEGORY_PRODUCT_UPDATE_REQUEST";
export const CATEGORY_PRODUCT_UPDATE_SUCCESS = "CATEGORY_PRODUCT_UPDATE_SUCCESS";
export const CATEGORY_PRODUCT_UPDATE_FAIL = "CATEGORY_PRODUCT_UPDATE_FAIL";
export const CATEGORY_PRODUCT_UPDATE_RESET = "CATEGORY_PRODUCT_UPDATE_RESET";